//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STM.Resources.Translations", typeof(Translations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API connection error ähnelt.
        /// </summary>
        public static string AccountModification_ApiConnectionError {
            get {
                return ResourceManager.GetString("AccountModification_ApiConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New account ähnelt.
        /// </summary>
        public static string AccountModification_NewAccount {
            get {
                return ResourceManager.GetString("AccountModification_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to locate an account, which can be updated. ähnelt.
        /// </summary>
        public static string AccountModification_NoMatchingAccountFound {
            get {
                return ResourceManager.GetString("AccountModification_NoMatchingAccountFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This account already exists ähnelt.
        /// </summary>
        public static string AccountModification_ThisAccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountModification_ThisAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use synchronization ähnelt.
        /// </summary>
        public static string AppSettingsView_UseSynchronization {
            get {
                return ResourceManager.GetString("AppSettingsView_UseSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collect tracing information? ähnelt.
        /// </summary>
        public static string GlobalSettingsView_CollectDebugTracing {
            get {
                return ResourceManager.GetString("GlobalSettingsView_CollectDebugTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transmit telemetry data? ähnelt.
        /// </summary>
        public static string GlobalSettingsView_TransmitTelemetryData {
            get {
                return ResourceManager.GetString("GlobalSettingsView_TransmitTelemetryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project loading ähnelt.
        /// </summary>
        public static string ProjectActionOverview_LoadInProgress {
            get {
                return ResourceManager.GetString("ProjectActionOverview_LoadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logged in as ähnelt.
        /// </summary>
        public static string ProjectActionOverview_LoggedInAs {
            get {
                return ResourceManager.GetString("ProjectActionOverview_LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Logout {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select project ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Project {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project has to be selected. ähnelt.
        /// </summary>
        public static string ProjectActionOverview_ProjectMustBeSelected {
            get {
                return ResourceManager.GetString("ProjectActionOverview_ProjectMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select site ähnelt.
        /// </summary>
        public static string ProjectActionOverview_ProjectStructure {
            get {
                return ResourceManager.GetString("ProjectActionOverview_ProjectStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Search {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Settings {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Status {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks / Incidents ähnelt.
        /// </summary>
        public static string ProjectActionOverview_Tasks {
            get {
                return ResourceManager.GetString("ProjectActionOverview_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown action ähnelt.
        /// </summary>
        public static string ProjectActionOverview_UnknownAction {
            get {
                return ResourceManager.GetString("ProjectActionOverview_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Inactive ähnelt.
        /// </summary>
        public static string SearchView_DisplayInactive {
            get {
                return ResourceManager.GetString("SearchView_DisplayInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Wbs ähnelt.
        /// </summary>
        public static string SearchView_DisplayWbs {
            get {
                return ResourceManager.GetString("SearchView_DisplayWbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No matches ähnelt.
        /// </summary>
        public static string SearchView_MessageNoResults {
            get {
                return ResourceManager.GetString("SearchView_MessageNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while loading permissions. Please check your account credentials. ähnelt.
        /// </summary>
        public static string SecurityManagerProxy_ErrorWhileLoadingPermissions {
            get {
                return ResourceManager.GetString("SecurityManagerProxy_ErrorWhileLoadingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string Shared_Abort {
            get {
                return ResourceManager.GetString("Shared_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account overview ähnelt.
        /// </summary>
        public static string Shared_AccountOverview {
            get {
                return ResourceManager.GetString("Shared_AccountOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Api URL ähnelt.
        /// </summary>
        public static string Shared_ApiUrl {
            get {
                return ResourceManager.GetString("Shared_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string Shared_AreYouSure {
            get {
                return ResourceManager.GetString("Shared_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to provide telemetry data to improve the user experience? ähnelt.
        /// </summary>
        public static string Shared_AskForTelemetryPermission {
            get {
                return ResourceManager.GetString("Shared_AskForTelemetryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to overview ähnelt.
        /// </summary>
        public static string Shared_BackToOverview {
            get {
                return ResourceManager.GetString("Shared_BackToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change settings ähnelt.
        /// </summary>
        public static string Shared_ChangeSettings {
            get {
                return ResourceManager.GetString("Shared_ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change view ähnelt.
        /// </summary>
        public static string Shared_ChangeView {
            get {
                return ResourceManager.GetString("Shared_ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard updated. ähnelt.
        /// </summary>
        public static string Shared_ClipboardUpdated {
            get {
                return ResourceManager.GetString("Shared_ClipboardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Shared_Close {
            get {
                return ResourceManager.GetString("Shared_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string Shared_Comment {
            get {
                return ResourceManager.GetString("Shared_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Shared_CommonInformation {
            get {
                return ResourceManager.GetString("Shared_CommonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to include remote data into this search query? ähnelt.
        /// </summary>
        public static string Shared_ConfirmRemoteLoad {
            get {
                return ResourceManager.GetString("Shared_ConfirmRemoteLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Shared_Create {
            get {
                return ResourceManager.GetString("Shared_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new account ähnelt.
        /// </summary>
        public static string Shared_CreateNewAccount {
            get {
                return ResourceManager.GetString("Shared_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date fields ähnelt.
        /// </summary>
        public static string Shared_DateFields {
            get {
                return ResourceManager.GetString("Shared_DateFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date fields ähnelt.
        /// </summary>
        public static string Shared_Dates {
            get {
                return ResourceManager.GetString("Shared_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discard ähnelt.
        /// </summary>
        public static string Shared_Discard {
            get {
                return ResourceManager.GetString("Shared_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domain ähnelt.
        /// </summary>
        public static string Shared_Domain {
            get {
                return ResourceManager.GetString("Shared_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        public static string Shared_Done {
            get {
                return ResourceManager.GetString("Shared_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Shared_Error {
            get {
                return ResourceManager.GetString("Shared_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field definitions ähnelt.
        /// </summary>
        public static string Shared_FieldDefinitions {
            get {
                return ResourceManager.GetString("Shared_FieldDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field values ähnelt.
        /// </summary>
        public static string Shared_FieldValues {
            get {
                return ResourceManager.GetString("Shared_FieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filters ähnelt.
        /// </summary>
        public static string Shared_Filter {
            get {
                return ResourceManager.GetString("Shared_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info fields ähnelt.
        /// </summary>
        public static string Shared_InfoFields {
            get {
                return ResourceManager.GetString("Shared_InfoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient permissions. ähnelt.
        /// </summary>
        public static string Shared_InsufficientPermissions {
            get {
                return ResourceManager.GetString("Shared_InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading &quot;{0}&quot; {1} ähnelt.
        /// </summary>
        public static string Shared_LoadingEntitiesFailed {
            get {
                return ResourceManager.GetString("Shared_LoadingEntitiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading permissions  ... {0} / {1} ähnelt.
        /// </summary>
        public static string Shared_LoadingPermissions_0_1 {
            get {
                return ResourceManager.GetString("Shared_LoadingPermissions_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading serviceprogram ähnelt.
        /// </summary>
        public static string Shared_LoadingServiceProgram {
            get {
                return ResourceManager.GetString("Shared_LoadingServiceProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main menu ähnelt.
        /// </summary>
        public static string Shared_MainMenu {
            get {
                return ResourceManager.GetString("Shared_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More ähnelt.
        /// </summary>
        public static string Shared_More {
            get {
                return ResourceManager.GetString("Shared_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to ähnelt.
        /// </summary>
        public static string Shared_NavigateTo {
            get {
                return ResourceManager.GetString("Shared_NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string Shared_No {
            get {
                return ResourceManager.GetString("Shared_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No child items available ähnelt.
        /// </summary>
        public static string Shared_NoChildElementsAvailable {
            get {
                return ResourceManager.GetString("Shared_NoChildElementsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no data available to display. ähnelt.
        /// </summary>
        public static string Shared_NoDataToDisplay {
            get {
                return ResourceManager.GetString("Shared_NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No report has been assigned. ähnelt.
        /// </summary>
        public static string Shared_NoReportAssigned {
            get {
                return ResourceManager.GetString("Shared_NoReportAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No serviceprogram available ähnelt.
        /// </summary>
        public static string Shared_NoServiceProgramAvailable {
            get {
                return ResourceManager.GetString("Shared_NoServiceProgramAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note ähnelt.
        /// </summary>
        public static string Shared_Note {
            get {
                return ResourceManager.GetString("Shared_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string Shared_OK {
            get {
                return ResourceManager.GetString("Shared_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open report ähnelt.
        /// </summary>
        public static string Shared_OpenReport {
            get {
                return ResourceManager.GetString("Shared_OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Shared_Password {
            get {
                return ResourceManager.GetString("Shared_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The permissions have changed since the last app launch. ähnelt.
        /// </summary>
        public static string Shared_PermissionsHaveChangedSinceLastLaunch {
            get {
                return ResourceManager.GetString("Shared_PermissionsHaveChangedSinceLastLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An api error occured which can occur because your account uses a http endpoint instead of https. Do you want to change your api connection to https? ähnelt.
        /// </summary>
        public static string Shared_PotentiallyInvalidApiEndpointConfigurationDetectedQuestion {
            get {
                return ResourceManager.GetString("Shared_PotentiallyInvalidApiEndpointConfigurationDetectedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project cannot be found ähnelt.
        /// </summary>
        public static string Shared_ProjectCannotBeFound {
            get {
                return ResourceManager.GetString("Shared_ProjectCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project overview ähnelt.
        /// </summary>
        public static string Shared_ProjectOverview {
            get {
                return ResourceManager.GetString("Shared_ProjectOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project selection ähnelt.
        /// </summary>
        public static string Shared_ProjectSelection {
            get {
                return ResourceManager.GetString("Shared_ProjectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project structure ähnelt.
        /// </summary>
        public static string Shared_ProjectStructureSingular {
            get {
                return ResourceManager.GetString("Shared_ProjectStructureSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string Shared_Question {
            get {
                return ResourceManager.GetString("Shared_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick action ähnelt.
        /// </summary>
        public static string Shared_QuickAction {
            get {
                return ResourceManager.GetString("Shared_QuickAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Shared_Save {
            get {
                return ResourceManager.GetString("Shared_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save changes? ähnelt.
        /// </summary>
        public static string Shared_SaveChangesConfirmation {
            get {
                return ResourceManager.GetString("Shared_SaveChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving failed ähnelt.
        /// </summary>
        public static string Shared_SavingFailed {
            get {
                return ResourceManager.GetString("Shared_SavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving successful ähnelt.
        /// </summary>
        public static string Shared_SavingSucceeded {
            get {
                return ResourceManager.GetString("Shared_SavingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Shared_Search {
            get {
                return ResourceManager.GetString("Shared_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serviceprogram ähnelt.
        /// </summary>
        public static string Shared_ServiceProgramSingular {
            get {
                return ResourceManager.GetString("Shared_ServiceProgramSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some validation rules are not satisfied ähnelt.
        /// </summary>
        public static string Shared_SomeConstraintsAreNotSatisfied {
            get {
                return ResourceManager.GetString("Shared_SomeConstraintsAreNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks ähnelt.
        /// </summary>
        public static string Shared_Tasks {
            get {
                return ResourceManager.GetString("Shared_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following user input is missing: {0} ähnelt.
        /// </summary>
        public static string Shared_TheFollowingInputsAreMissing {
            get {
                return ResourceManager.GetString("Shared_TheFollowingInputsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview ähnelt.
        /// </summary>
        public static string Shared_ToOverview {
            get {
                return ResourceManager.GetString("Shared_ToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application log ähnelt.
        /// </summary>
        public static string Shared_TraceView {
            get {
                return ResourceManager.GetString("Shared_TraceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The url &quot;{0}&quot; could not be opened. ähnelt.
        /// </summary>
        public static string Shared_UrlCouldNotBeOpened_0 {
            get {
                return ResourceManager.GetString("Shared_UrlCouldNotBeOpened_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Shared_UserName {
            get {
                return ResourceManager.GetString("Shared_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation errors ähnelt.
        /// </summary>
        public static string Shared_ValidationErrors {
            get {
                return ResourceManager.GetString("Shared_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Shared_Yes {
            get {
                return ResourceManager.GetString("Shared_Yes", resourceCulture);
            }
        }
    }
}
